### ISSUE TITLE
New features for Motoko 0.7.0

### ISSUE THREAD

**Issue by skilesare** [DanielXMoore/kusanagi#15]
https://github.com/dfinity/motoko/releases/tag/0.7.0

A couple of new things were added.

One of the most useful is the 

```
{ baseA and baseB with field1 = val1; field2 = val2 }
```

Which is like the spread operator in js. something like the below would be cool:

```

let x =
   ...baseA
   ...baseB
   field1 = val1
   field2 = val2
```

**Comment by STRd6** [comment]
Fixed in c2d25ee13d9a5c430ef00fec9d400f252c9193b9
